# Definindo o nome do workflow
name: Test Workflow

# Definindo quando o workflows será disparado
on:
  push:
    branches: [main, developer]

# Definindo os jobs que o workflow wxecutará
jobs:
  test_job:
    name: Executando job de teste
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Executando um comando simples
      run: echo "Olá, mundo! Este é o primeiro job no Github Actions"
